"""Orchestrator: pull all ground-truth sources and write the unified CSV.

Run as a module:
    python -m ground_truth.build

Sources currently wired up:
  - sports-reference.com: MLB (Yankees, Mets), NBA (Knicks, Nets), NHL (Rangers)
  - hand-curated: civic, US Open sessions, sports playoffs
  - setlist.fm API: concerts at MSG and Barclays
  - NYC Open Data parade permits (no-op; dataset doesn't carry 2024 history)

Outputs:
  - data/processed/ground_truth_events.csv (canonical event list)
  - data/processed/ground_truth_report.md (yield + sanity summary)
"""
from __future__ import annotations

import logging
from io import StringIO

import pandas as pd

from ingest.config import DATA_PROCESSED

from . import config
from .schema import events_to_dataframe
from .sources import handcurated, mlb, nba, nhl, parades, setlist_fm

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("ground_truth.build")


SOURCES = [
    ("mlb_regular",      mlb.collect),
    ("nba_regular",      nba.collect),
    ("nhl_regular",      nhl.collect),
    ("playoffs",         handcurated.collect_playoffs),
    ("civic_seed",       handcurated.collect_civic),
    ("us_open_seed",     handcurated.collect_us_open),
    ("nyc_parades",      parades.collect),
    ("setlist_fm",       setlist_fm.collect),
]


def build_report(df: pd.DataFrame, per_source: dict[str, int]) -> str:
    buf = StringIO()
    buf.write("# Ground Truth Events — 2024\n\n")
    buf.write(
        "*Generated by `ground_truth.build`. Each row in "
        "`data/processed/ground_truth_events.csv` corresponds to one\n"
        "discrete event at one of the five archetype stations.*\n"
    )

    # --- yield per source ---------------------------------------------------
    buf.write("\n## Events per source\n\n")
    src_table = pd.DataFrame(
        sorted(per_source.items(), key=lambda kv: -kv[1]),
        columns=["source_label", "count"],
    )
    buf.write(src_table.to_markdown(index=False) + "\n")
    buf.write(f"\n**Total rows (pre-dedup):** {sum(per_source.values())}\n")
    buf.write(f"**Total rows (post-dedup by event_id):** {len(df)}\n")

    # --- yield per (target × event_type) ------------------------------------
    buf.write("\n## Events per (target × event_type)\n\n")
    pivot = (
        df.groupby(["target_key", "event_type"])
        .size()
        .unstack("event_type", fill_value=0)
    )
    buf.write(pivot.to_markdown() + "\n")

    # --- date coverage ------------------------------------------------------
    buf.write("\n## Date coverage\n\n")
    dates = pd.to_datetime(df["date"])
    buf.write(f"- Earliest event: **{dates.min().date()}**\n")
    buf.write(f"- Latest event:   **{dates.max().date()}**\n")
    monthly = (
        df.assign(month=pd.to_datetime(df["date"]).dt.to_period("M").astype(str))
        .groupby("month")
        .size()
        .reset_index(name="events")
    )
    buf.write("\nMonthly counts:\n\n")
    buf.write(monthly.to_markdown(index=False) + "\n")

    # --- spot checks for the residual report ---------------------------------
    buf.write("\n## Spot-check matches against the +15,507 Yankee residual\n\n")
    yk_oct29 = df[(df["target_key"] == "yankee") & (df["date"] == "2024-10-29")]
    if not yk_oct29.empty:
        buf.write(
            "Yankee Stadium event on 2024-10-29 (the hour with the biggest "
            "residual from the baseline report):\n\n"
        )
        buf.write(yk_oct29[["event_name", "event_type", "start_time", "end_time"]].to_markdown(index=False) + "\n")
    else:
        buf.write("**WARNING:** no event for 2024-10-29 at yankee — World Series Game 4 expected.\n")

    nye = df[(df["target_key"] == "times_sq") & (df["date"] == "2024-12-31")]
    buf.write("\nTimes Sq events on 2024-12-31 (NYE):\n\n")
    buf.write(nye[["event_name", "event_type", "start_time", "end_time"]].to_markdown(index=False) + "\n")

    return buf.getvalue()


def main() -> int:
    all_events = []
    per_source: dict[str, int] = {}
    for label, fn in SOURCES:
        log.info("--- running source: %s ---", label)
        try:
            evs = fn()
        except Exception as e:
            log.error("[%s] failed: %s", label, e)
            evs = []
        per_source[label] = len(evs)
        all_events.extend(evs)

    df = events_to_dataframe(all_events)
    out = config.EVENTS_CSV
    df.to_csv(out, index=False)
    log.info("Wrote %s (%d rows)", out, len(df))

    report = build_report(df, per_source)
    report_path = DATA_PROCESSED / "ground_truth_report.md"
    report_path.write_text(report)
    log.info("Wrote %s", report_path)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
