"""Apply detection to the full 2024 time series and write outputs.

Run as a module:
    python -m anomaly.build

Inputs:
    data/processed/ridership_with_baseline.parquet  (from baseline.build)

Outputs:
    data/processed/ridership_with_anomaly.parquet
        all 52,704 hourly rows × full feature set (baseline, ratio,
        z-score, all four flags). Downstream code joins against this.

    data/processed/flagged_anomalies.parquet
        the subset that triggers any flag — much smaller, what the
        matcher in Phase 2 will work against.

    data/processed/anomaly_report.md
        flag-method comparison per archetype + top hits sanity check.
"""
from __future__ import annotations

import logging
from io import StringIO

import pandas as pd

from ingest.config import DATA_PROCESSED

from .detect import detect

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("anomaly.build")


RATIO_THRESHOLD = 1.5
Z_THRESHOLD = 3.0


def build_report(df: pd.DataFrame) -> str:
    buf = StringIO()
    buf.write("# Anomaly Detection Report — 2024\n\n")
    buf.write(
        f"*Generated by `anomaly.build`. Thresholds: ratio ≥ {RATIO_THRESHOLD}, "
        f"z ≥ {Z_THRESHOLD} over rolling 4 same-hour-of-week observations.*\n"
    )

    # ---- counts per archetype --------------------------------------------
    buf.write("\n## Flag counts per archetype\n\n")
    counts = (
        df.groupby("target_key")[["flag_ratio", "flag_z", "flag_either", "flag_both"]]
        .sum()
        .astype(int)
        .reset_index()
    )
    counts["total_hours"] = df.groupby("target_key").size().values
    counts["ratio_pct"] = (counts["flag_ratio"] / counts["total_hours"] * 100).round(2)
    counts["z_pct"] = (counts["flag_z"] / counts["total_hours"] * 100).round(2)
    buf.write(counts.to_markdown(index=False) + "\n")

    # ---- per-complex counts ----------------------------------------------
    buf.write("\n## Flag counts per complex_id\n\n")
    by_complex = (
        df.groupby(["target_key", "station_complex_id"])[["flag_ratio", "flag_z", "flag_either", "flag_both"]]
        .sum().astype(int).reset_index()
    )
    buf.write(by_complex.to_markdown(index=False) + "\n")

    # ---- agreement of the two methods ------------------------------------
    buf.write("\n## Agreement between ratio and z\n\n")
    buf.write("Cross-tab of `flag_ratio` × `flag_z` (counts of hourly rows):\n\n")
    xt = pd.crosstab(df["flag_ratio"], df["flag_z"], rownames=["flag_ratio"], colnames=["flag_z"])
    buf.write(xt.to_markdown() + "\n")
    only_ratio = int(((df["flag_ratio"]) & (~df["flag_z"])).sum())
    only_z = int(((~df["flag_ratio"]) & (df["flag_z"])).sum())
    both = int(((df["flag_ratio"]) & (df["flag_z"])).sum())
    buf.write(
        f"\n- Ratio-only: **{only_ratio}** flagged hours\n"
        f"- Z-only:     **{only_z}** flagged hours\n"
        f"- Both:       **{both}** flagged hours\n"
    )

    # ---- top hits sanity --------------------------------------------------
    buf.write("\n## Top flagged hours per archetype (by anomaly_score)\n\n")
    flagged = df[df["flag_either"]]
    for tk in sorted(df["target_key"].unique()):
        sub = (
            flagged[flagged["target_key"] == tk]
            .sort_values("anomaly_score", ascending=False)
            .head(10)
            [["transit_timestamp", "station_complex_id", "ridership",
              "baseline_ridership", "anomaly_ratio", "z_score",
              "flag_ratio", "flag_z"]]
            .round(2)
        )
        buf.write(f"### {tk}\n\n")
        if sub.empty:
            buf.write("*(none flagged)*\n\n")
            continue
        buf.write(sub.to_markdown(index=False) + "\n\n")

    return buf.getvalue()


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--suffix",
        default="",
        help="If set (e.g. '_v2'), reads ridership_with_baseline{suffix}.parquet "
             "and writes ridership_with_anomaly{suffix}.parquet etc.",
    )
    args = parser.parse_args(argv)
    suf = args.suffix

    src = DATA_PROCESSED / f"ridership_with_baseline{suf}.parquet"
    log.info("Loading %s", src)
    df = pd.read_parquet(src)
    log.info("Loaded %d rows", len(df))

    out = detect(df, ratio_threshold=RATIO_THRESHOLD, z_threshold=Z_THRESHOLD)

    full_out = DATA_PROCESSED / f"ridership_with_anomaly{suf}.parquet"
    out.to_parquet(full_out, index=False)
    log.info("Wrote %s (%d rows)", full_out, len(out))

    flagged = out[out["flag_either"]].copy()
    flag_out = DATA_PROCESSED / f"flagged_anomalies{suf}.parquet"
    flagged.to_parquet(flag_out, index=False)
    log.info(
        "Wrote %s (%d flagged hours, %.2f%% of all hours)",
        flag_out, len(flagged), 100 * len(flagged) / len(out),
    )

    report = build_report(out)
    report_path = DATA_PROCESSED / f"anomaly_report{suf}.md"
    report_path.write_text(report)
    log.info("Wrote %s", report_path)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
