"""Refit baselines excluding known event hours.

Motivation: at high-event-density venues (Penn Station / MSG above all),
the naive median baseline is contaminated — too many summer Fridays at
Yankee are game days, too many Knicks Tuesday evenings include a Knicks
home game. The median lands at a partially-event-influenced level and
moderate-attendance events stop being detectable.

Fix: now that we have `ground_truth_events.csv`, exclude any hour that
falls inside an event's ±3h window from the baseline-input pool.
Federal holidays and NaN hours are still excluded as in the naive
baseline.

Run as a module:
    python -m baseline.refit

Outputs:
    data/processed/baselines_v2.parquet
    data/processed/ridership_with_baseline_v2.parquet
    data/processed/baseline_refit_report.md
"""
from __future__ import annotations

import logging
from datetime import datetime, time, timedelta
from io import StringIO

import pandas as pd

from ingest.config import DATA_PROCESSED, TARGETS

from ground_truth import config as gt_config

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("baseline.refit")


WINDOW_HOURS = 3            # same symmetric ±3h used by the matcher
MIN_EVENT_DURATION = timedelta(hours=1)


def _target_to_complex_ids() -> dict[str, list[str]]:
    return {t.key: list(t.complex_ids) for t in TARGETS}


def _build_event_windows(events: pd.DataFrame) -> pd.DataFrame:
    """Attach window_start / window_end datetimes for every event row."""
    out = events.copy()
    out["date"] = pd.to_datetime(out["date"]).dt.date

    def to_dt(d, t_str, fallback: time) -> datetime:
        if pd.isna(t_str):
            t = fallback
        else:
            t = datetime.strptime(str(t_str), "%H:%M").time()
        return datetime.combine(d, t)

    starts = [to_dt(d, s, time(18, 0)) for d, s in zip(out["date"], out["start_time"])]
    ends = []
    for d, e, st in zip(out["date"], out["end_time"], starts):
        ends.append(to_dt(d, e, (st + MIN_EVENT_DURATION).time()))

    out["window_start"] = [s - timedelta(hours=WINDOW_HOURS) for s in starts]
    out["window_end"] = [e + timedelta(hours=WINDOW_HOURS) for e in ends]
    return out


def mark_event_hours(ridership: pd.DataFrame, events_w: pd.DataFrame) -> pd.Series:
    """Boolean mask, True if (timestamp, target_key) is in any event window."""
    ts = pd.to_datetime(ridership["transit_timestamp"])
    out = pd.Series(False, index=ridership.index)
    for tk, group in events_w.groupby("target_key"):
        mask_target = (ridership["target_key"] == tk).to_numpy()
        if not mask_target.any():
            continue
        ts_target = ts[mask_target]
        in_any = pd.Series(False, index=ts_target.index)
        for ws, we in zip(group["window_start"], group["window_end"]):
            in_any |= (ts_target >= ws) & (ts_target <= we)
        out.loc[ts_target.index] = in_any
    return out


def compute_v2_baselines(df: pd.DataFrame) -> pd.DataFrame:
    """Per-(complex_id, season, dow, hour) median over the cleaned pool."""
    pool = df.loc[
        ~df["is_federal_holiday"]
        & df["ridership"].notna()
        & ~df["in_event_window"]
    ]
    return (
        pool.groupby(
            ["station_complex_id", "season", "day_of_week", "hour"],
            observed=True,
            as_index=False,
        )["ridership"]
        .agg(baseline_ridership="median", n_observations="count")
    )


def attach_v2(ridership: pd.DataFrame, baselines_v2: pd.DataFrame) -> pd.DataFrame:
    keys = ["station_complex_id", "season", "day_of_week", "hour"]
    cols_to_drop = ["baseline_ridership", "n_observations", "residual"]
    base = ridership.drop(columns=[c for c in cols_to_drop if c in ridership.columns])
    merged = base.merge(
        baselines_v2[keys + ["baseline_ridership", "n_observations"]],
        on=keys, how="left", validate="many_to_one",
    )
    merged["residual"] = merged["ridership"] - merged["baseline_ridership"]
    return merged


def _build_report(
    base_v1: pd.DataFrame,
    base_v2: pd.DataFrame,
    ts_v1: pd.DataFrame,
    ts_v2: pd.DataFrame,
    exclusion_counts: pd.DataFrame,
) -> str:
    buf = StringIO()
    buf.write("# Baseline Refit Report — Event-Aware\n\n")
    buf.write(
        "*Generated by `baseline.refit`. The v2 baseline excludes any "
        "hour that falls within an event's ±3h window from the "
        "median-input pool. Federal holidays remain excluded as in v1.*\n"
    )

    # ---- exclusion volume -------------------------------------------------
    buf.write("\n## Hours excluded by target\n\n")
    buf.write(exclusion_counts.to_markdown(index=False) + "\n")

    # ---- baseline shift ---------------------------------------------------
    merged = base_v1.merge(
        base_v2,
        on=["station_complex_id", "season", "day_of_week", "hour"],
        suffixes=("_v1", "_v2"),
    )
    merged["delta"] = merged["baseline_ridership_v2"] - merged["baseline_ridership_v1"]
    merged["pct"] = (merged["delta"] / merged["baseline_ridership_v1"]) * 100

    buf.write("\n## Per-(target × complex × season) baseline shift\n\n")
    # We need target_key in the rows; baselines table doesn't carry it, but
    # we can infer it from station_complex_id via the targets registry.
    cid_to_target = {cid: t.key for t in TARGETS for cid in t.complex_ids}
    merged["target_key"] = merged["station_complex_id"].map(cid_to_target)
    summary = (
        merged.groupby(["target_key", "station_complex_id", "season"], observed=True)
        .agg(
            cells=("delta", "size"),
            median_baseline_v1=("baseline_ridership_v1", "median"),
            median_baseline_v2=("baseline_ridership_v2", "median"),
            median_delta=("delta", "median"),
            median_pct_change=("pct", "median"),
        )
        .round(2)
        .reset_index()
    )
    buf.write(summary.to_markdown(index=False) + "\n")
    buf.write(
        "\n*Negative `median_delta` means the v2 baseline dropped after "
        "excluding event hours — i.e., event hours had been inflating the "
        "naive median. The bigger the drop, the more contaminated v1 was.*\n"
    )

    # ---- spot check: MSG Tuesday evening ---------------------------------
    buf.write("\n## Spot check: MSG complex 318, Tuesday evening 18-22h\n\n")
    spot = merged[
        (merged["station_complex_id"] == "318")
        & (merged["day_of_week"] == 1)
        & (merged["hour"].between(18, 22))
    ].sort_values(["season", "hour"])[
        ["season", "hour", "baseline_ridership_v1", "baseline_ridership_v2", "delta", "pct"]
    ].round(2)
    buf.write(spot.to_markdown(index=False) + "\n")

    # ---- pool size adequacy -----------------------------------------------
    buf.write("\n## Pool size — observations per baseline cell\n\n")
    cells = (
        base_v2.groupby(["station_complex_id", "season"], observed=True)
        ["n_observations"].describe()
        .round(1)
    )
    buf.write(cells.to_markdown() + "\n")
    n_below_5 = int((base_v2["n_observations"] < 5).sum())
    n_below_10 = int((base_v2["n_observations"] < 10).sum())
    buf.write(f"\n- Cells with n < 5:  **{n_below_5}**\n")
    buf.write(f"- Cells with n < 10: **{n_below_10}**\n")

    return buf.getvalue()


def main() -> int:
    ridership_v1_path = DATA_PROCESSED / "ridership_with_baseline.parquet"
    baselines_v1_path = DATA_PROCESSED / "baselines.parquet"
    events_path = gt_config.EVENTS_CSV

    log.info("Loading naive baseline outputs ...")
    ridership = pd.read_parquet(ridership_v1_path)
    base_v1 = pd.read_parquet(baselines_v1_path)
    log.info("Loaded ridership (%d rows), baselines_v1 (%d cells)", len(ridership), len(base_v1))

    log.info("Loading ground truth events ...")
    events = pd.read_csv(events_path)
    events_w = _build_event_windows(events)
    log.info("Loaded %d events; expanded to ±%dh windows", len(events_w), WINDOW_HOURS)

    log.info("Marking event-window hours ...")
    ridership["in_event_window"] = mark_event_hours(ridership, events_w)

    # Compose exclusion summary per target before recomputing the baseline.
    exclusion_counts = (
        ridership.groupby("target_key")
        .agg(
            total_hours=("transit_timestamp", "size"),
            holiday_hours=("is_federal_holiday", "sum"),
            event_window_hours=("in_event_window", "sum"),
            nan_ridership_hours=("ridership", lambda s: int(s.isna().sum())),
        )
        .reset_index()
    )
    exclusion_counts["pool_remaining"] = (
        exclusion_counts["total_hours"]
        - exclusion_counts["holiday_hours"]
        - exclusion_counts["event_window_hours"]
        - exclusion_counts["nan_ridership_hours"]
    )
    exclusion_counts["pct_excluded"] = (
        100 * (1 - exclusion_counts["pool_remaining"] / exclusion_counts["total_hours"])
    ).round(2)

    log.info("Computing v2 baselines ...")
    base_v2 = compute_v2_baselines(ridership)
    log.info("v2 baselines: %d cells", len(base_v2))

    log.info("Attaching v2 baselines back to ridership ...")
    ridership_v2 = attach_v2(ridership, base_v2)

    ridership_v2_path = DATA_PROCESSED / "ridership_with_baseline_v2.parquet"
    baselines_v2_path = DATA_PROCESSED / "baselines_v2.parquet"
    ridership_v2.to_parquet(ridership_v2_path, index=False)
    base_v2.to_parquet(baselines_v2_path, index=False)
    log.info("Wrote %s (%d rows)", ridership_v2_path, len(ridership_v2))
    log.info("Wrote %s (%d cells)", baselines_v2_path, len(base_v2))

    report = _build_report(base_v1, base_v2, ridership, ridership_v2, exclusion_counts)
    report_path = DATA_PROCESSED / "baseline_refit_report.md"
    report_path.write_text(report)
    log.info("Wrote %s", report_path)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
